### PR TITLE
245 fix mobile interactivity with location points

### LINKED ISSUE #245: Fix mobile interactivity with location points

### PR DESCRIPTION
**Pull request by hvangeffen**
closes #245

### CODE REVIEW

File: src/views/MetocDataView.vue [hunk 1]
```diff
@@ -742,7 +754,7 @@ export default class MetocDataView extends Mixins(WMSMixin, TimeSeriesMixin) {
   }
 
   get showMap(): boolean {
-    const isMobileGraphOpen = this.hasSelectedLocation && this.$vuetify.breakpoint.mobile
+    const isMobileGraphOpen = this.hasDataToDisplay && this.$vuetify.breakpoint.mobile
```
Comment (hvangeffen) [inline src/views/MetocDataView.vue:757]: `hasDataToDisplay` was added to generalize this check for any data that has to be displayed, as one of the bugs fixed with this is data the map did not close on mobile breakpoints when a coordinate was selected.
